name: intel-npu
description: Use Intel NPUs (Core Ultra series)
vendor: Intel Corporation
grade: stable
devices:
  all:
    - type: cpu
      architecture: amd64
  any:    
    # Lunar Lake NPU
    - type: npu
      vendor-id: 0x8086 # Intel Corporation
      device-id: 0x643e 
    # Meteor Lake NPU
    - type: npu
      vendor-id: 0x8086
      device-id: 0x7d1d

memory: 4G
disk-space: 8G
components:
  - &e openvino-model-server
  - &m model-qwen2-5-vl-7b-instruct-ov-int4
configurations:
  engine: *e
  model: *m
  target-device: NPU
  model-name: Qwen2.5-VL-7B-Instruct-openvino-int4
  http.base-path: v3
