#!/bin/bash -eux

# Use parent directory name as component name
component_name=$(dirname "$(readlink -f "$0")")
#component_name=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
#component_name=llamacpp

component_directory=$SNAP_COMPONENTS/$component_name/

snapctl set engine-type="llamacpp"
snapctl set engine-executable="$component_directory/usr/local/bin/llama-server"
snapctl set engine-additional-ldlib-path="$component_directory/usr/lib/$ARCH_TRIPLET:$component_directory/usr/local/lib"
