#!/bin/bash -eu

component_directory=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

model_filename="Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf"
model_path=$component_directory/$model_filename
snapctl set model-file-path="$model_path"
