#!/bin/bash -eu

component_name=model-qwen2-5-vl-7b-instruct-q4-k-m

model_filename=Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf
model_path=$SNAP_COMPONENTS/$component_name/$model_filename
export MODEL_FILE=$model_path
