name: intel-cpu
description: Use Intel CPUs
vendor: Intel Corporation
grade: stable
devices:
  all:
    - type: cpu
      architecture: amd64
      manufacturer-id: GenuineIntel

memory: 4G
disk-space: 8G
components:
  - &e openvino-model-server
  - &m model-qwen2-5-vl-3b-instruct-ov-int4
configurations:
  engine: *e
  model: *m
  target-device: CPU
  model-name: Qwen2.5-VL-3B-Instruct-openvino-int4
  http.base-path: v3
