#!/bin/bash -eu

source "$(dirname "$0")/common.sh"

port="$(qwen-vl get http.port)"
host="$(qwen-vl get http.host)"

extra_args=()

verbose="$(qwen-vl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

gpu_layers="$(qwen-vl get gpu-layers)"
if [[ -z "$gpu_layers" ]]; then
  echo "gpu-layers snap option is not set"
  exit 1
fi

exec "$server/usr/local/bin/llama-server" \
--model "$MODEL_FILE" \
--mmproj "$MMPROJ_FILE" \
--port "$port" \
--host "$host" \
--n-gpu-layers "$gpu_layers" \
"${extra_args[@]}" \
"$@"
