#!/bin/bash -eu

source "$(dirname "$0")/common.sh"

port="$(qwen-vl get http.port)"
host="$(qwen-vl get http.host)"

extra_args=()

verbose="$(qwen-vl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--verbose)
fi

exec "$server/bin/llama-server" \
--model "$MODEL_FILE" \
--mmproj "$MMPROJ_FILE" \
--port "$port" \
--host "$host" \
--threads 40 \
--threads-batch 40 \
--no-mmap \
"${extra_args[@]}" \
"$@"
