#!/bin/bash -eu

# TODO: should most of this script move to the ovms component?

server_path="$SNAP_COMPONENTS/$(qwen-vl get server)"
if [ ! -d "$server_path" ]; then
    echo "Missing component: $server_path"
    exit 1
fi

model_path="$SNAP_COMPONENTS/$(qwen-vl get model)"
if [ ! -d "$model_path" ]; then
    echo "Missing component: $model_path"
    exit 1
fi

# Model component init exports MODEL_NAME
source "$model_path/init"

# Add staged shared objects
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$server_path/lib"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$server_path/lib/python"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$server_path/usr/lib/$ARCH_TRIPLET"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/usr/local/lib"
export LD_LIBRARY_PATH
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

# To find the intel.icd file, containing the path to libigdrcl.so
export OCL_ICD_VENDORS=$SNAP/etc/OpenCL/vendors

# Add Python dependencies
export PYTHONPATH="$server_path/lib/python:$server_path/lib/python3.12/site-packages"
echo "PYTHONPATH: $PYTHONPATH"

target_device="$(qwen-vl get target-device)"
if [ -z "$target_device" ]; then
    echo "target-device configuration not set!"
    exit 1
fi

port="$(qwen-vl get http.port)"
host="$(qwen-vl get http.host)"

extra_args=()

verbose="$(qwen-vl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--log_level DEBUG)
fi

# The --source_model and --model_repository_path args are pull-related arguments.
# OVMS does not work when using the alternative --model_name and --model_path arguments.
# Issue: https://github.com/openvinotoolkit/model_server/issues/3492

set -x
"$server_path/bin/ovms" \
    --rest_port "$port" \
    --rest_bind_address "$host" \
    --source_model "$MODEL_NAME" \
    --model_repository_path "$model_path" \
    --target_device "$target_device" \
    --task text_generation \
    --cache_size 2 \
    "${extra_args[@]}" \
    "$@"
