#!/bin/bash -eu

# TODO: should most of this script move to the ovms component?

engine_component_path="$SNAP_COMPONENTS/$(snapctl get engine)"
if [ ! -d "$engine_component_path" ]; then
    echo "Missing component: $engine_component_path"
    exit 1
fi

model_component_path="$SNAP_COMPONENTS/$(snapctl get model)"
if [ ! -d "$model_component_path" ]; then
    echo "Missing component: $model_component_path"
    exit 1
fi

"$model_component_path/init"

model_name="$(snapctl get model-name)"
if [ -z "$model_name" ]; then
    echo "model_name configuration not set"
    exit 1
fi

# Add staged shared objects
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$engine_component_path/lib"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$engine_component_path/lib/python"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$engine_component_path/usr/lib/$ARCH_TRIPLET"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/usr/local/lib"
export LD_LIBRARY_PATH
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

# To find the intel.icd file, containing the path to libigdrcl.so
export OCL_ICD_VENDORS=$SNAP/etc/OpenCL/vendors

# Add Python dependencies
export PYTHONPATH="$engine_component_path/lib/python:$engine_component_path/lib/python3.12/site-packages"
echo "PYTHONPATH: $PYTHONPATH"

target_device="$(snapctl get target-device)"
if [ -z "$target_device" ]; then
    echo "target-device configuration not set!"
    exit 1
fi

port="$(snapctl get http.port)"
host="$(snapctl get http.host)"

extra_args=()

verbose="$(snapctl get verbose)"
if [ "${verbose}" = "true" ]; then
  extra_args+=(--log_level DEBUG)
fi

# The --source_model and --model_repository_path args are pull-related arguments.
# OVMS does not work when using the alternative --model_name and --model_path arguments.
# Issue: https://github.com/openvinotoolkit/model_server/issues/3492

set -x
$engine_component_path/bin/ovms \
    --rest_port "$port" \
    --rest_bind_address "$host" \
    --source_model "$model_name" \
    --model_repository_path "$model_component_path" \
    --target_device "$target_device" \
    --task text_generation \
    --cache_size 2 \
    "${extra_args[@]}"
    "$@"
