name: qwen-vl
base: core24
summary: Qwen 2.5 VL inference snap
description: |
  Qwen 2.5 VL is a vision language model from Alibaba Cloud.

  Use this snap to run Qwen 2.5 VL, optimized for your silicon.

  Before you start, make sure to have the necessary drivers installed on the host:
  https://documentation.ubuntu.com/inference-snaps/how-to/setup/drivers/

  **Install:**
  
  `sudo snap install qwen-vl`
  
  **Get help:**
  
  `qwen-vl --help`
  
  **Licensing:**
  
  The Qwen 2.5 VL model is licensed under Apache 2.0.

  The licenses of all bundled software can be found after installing the snap at `/snap/qwen-vl/current/usr/share/doc`.
website: https://documentation.ubuntu.com/inference-snaps
source-code: https://github.com/canonical/qwen-vl-snap
issues: https://github.com/canonical/inference-snaps/issues

adopt-info: version

grade: stable
confinement: strict
compression: lzo

assumes:
  - snapd2.68 # for components support


platforms:
  amd64:
  arm64:

slots:
  status:
    interface: content
    source:
      read:
        - &status-share $SNAP_DATA/share/status
  open-webui:
    interface: content
    content: open-webui-config
    source:
      read:
        - &owui-share $SNAP_DATA/share/open-webui

plugs:
  intel-npu:
    interface: custom-device
    custom-device: intel-npu-device
  npu-libs:
    interface: content
    content: npu-libs-2404
    target: $SNAP/npu-libs
  # To allow sideloading models by root
  home:
    read: all

environment:
  SNAP_COMPONENTS: /snap/$SNAP_INSTANCE_NAME/components/$SNAP_REVISION
  ARCH_TRIPLET: $CRAFT_ARCH_TRIPLET_BUILD_FOR
  STATUS_SHARE: *status-share # Status directory shared via content interface
  OWUI_SHARE: *owui-share # Open WebUI config directory shared via content interface
  # This is to find the intel.icd file, containing the path to libigdrcl.so
  # Required for Intel GPU detection and communication
  OCL_ICD_VENDORS: $SNAP/etc/OpenCL/vendors

layout:
  # OpenCL looks in /etc/OpenCL/vendors for .icd files containing the paths to shared objects
  /etc/OpenCL/vendors:
    bind: $SNAP/etc/OpenCL/vendors
  # Intel icd files use an absolute path to Intel OpenCL shared objects. Use a layout to mount the so files at the expected location
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl
  # Under wsl the libraries are expected in /usr/lib/wsl
  /usr/lib/wsl:
    bind: $SNAP_COMMON/usr/lib/wsl

hooks:
  install:
    plugs: &install-plugs
      # For hardware detection
      - hardware-observe
      - opengl
  post-refresh:
    plugs: *install-plugs


parts:
  version:
    after: [cli]
    plugin: nil
    source: . # To regenerate the git hash on every change
    build-packages:
      - jq
      - git
    override-pull: |
      # Do nothing. This significantly reduces build time when sourcing large files.
    override-build: |
      set -eo pipefail
      cli_version=$($CRAFT_STAGE/bin/modelctl version --format=json | jq .cli --raw-output)
      git_hash=$(git -C "$SNAPCRAFT_PROJECT_DIR" describe --always)
      craftctl set version="${cli_version#v}+${git_hash}"

  cli:
    source:
      - on amd64: https://github.com/canonical/inference-snaps-cli/releases/download/v2.0.0-beta.5/inference-snaps-cli-linux-amd64.tar.xz
      - on arm64: https://github.com/canonical/inference-snaps-cli/releases/download/v2.0.0-beta.5/inference-snaps-cli-linux-arm64.tar.xz
    plugin: dump
    override-build: |
      # For tab completion
      ln --symbolic ./modelctl bin/qwen-vl

      craftctl default

  cli-dependencies:
    plugin: nil
    stage-packages:
      - pciutils # lspci
      - clinfo # used for Intel GPU vRAM detection. It depends on intel-opencl-icd

  # Used for NVIDIA vRAM and CUDA Capability detection.
  # Only the binary is included to avoid staging libraries, which should instead be provided by the host through the opengl interface.
  cli-nvidia-smi:
    plugin: nil
    build-packages:
      - nvidia-utils-580
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp /usr/bin/nvidia-smi $CRAFT_PART_INSTALL/usr/bin/
      
      license_dir=$CRAFT_PART_INSTALL/usr/share/doc/nvidia-utils-580/
      mkdir -p $license_dir
      cp /usr/share/doc/nvidia-utils-580/copyright $license_dir/

  opencl-driver:
    # Includes the OpenCL runtime for Intel GPU support
    plugin: nil
    build-packages:
      - wget
    override-build: |
      # Only install intel opencl drivers on amd64
      if [ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ]; then
        # Legacy Intel OpenCL Runtime
        mkdir -p $CRAFT_PART_BUILD/opencl-intel-legacy1
        cd $CRAFT_PART_BUILD/opencl-intel-legacy1
        wget https://github.com/intel/compute-runtime/releases/download/24.35.30872.36/intel-level-zero-gpu-legacy1_1.5.30872.36_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/24.35.30872.36/intel-opencl-icd-legacy1_24.35.30872.36_amd64.deb
        dpkg --root=$CRAFT_PART_INSTALL --force-all -i *.deb
      
        # Recent Intel OpenCL Runtime
        mkdir -p $CRAFT_PART_BUILD/opencl-intel
        cd $CRAFT_PART_BUILD/opencl-intel
        wget https://github.com/intel/intel-graphics-compiler/releases/download/v2.5.6/intel-igc-core-2_2.5.6+18417_amd64.deb
        wget https://github.com/intel/intel-graphics-compiler/releases/download/v2.5.6/intel-igc-opencl-2_2.5.6+18417_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/intel-level-zero-gpu_1.6.32224.5_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/intel-opencl-icd_24.52.32224.5_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/libigdgmm12_22.5.5_amd64.deb
        dpkg --root=$CRAFT_PART_INSTALL --force-all -i *.deb
      
        # Two symlinks are created by installing opencl: 
        # etc/alternatives/ocloc -> /usr/bin/ocloc-24.52.1, usr/bin/ocloc -> /etc/alternatives/ocloc
        # These point to outside of the snap and fails store review. They are not required, so remove it.
        rm $CRAFT_PART_INSTALL/etc/alternatives/ocloc
        rm $CRAFT_PART_INSTALL/usr/bin/ocloc
      
        cd $CRAFT_PART_BUILD
      fi # End of intel-opencl driver installation
      
      craftctl default

  webui:
    plugin: dump
    source: https://github.com/canonical/inference-snaps-webui/releases/download/v1.1.0/inference-snaps-webui.tar.xz
    organize:
      "*": webui/

  engines:
    source: engines
    plugin: dump
    organize:
      "*": engines/

  models:
    source: models
    plugin: dump
    organize:
      "*": models/

  runtimes:
    source: runtimes
    plugin: dump
    organize:
      "*": runtimes/

  scripts:
    source: scripts
    plugin: dump
    stage-packages:
      - jq
    organize:
      "server.sh": bin/
      "server-webui.sh": bin/
      "export-shared-configs.sh": bin/
      
  local-component-files:
     # Use the cmake plugin instead of "dump" to prevent unwanted copies
     # See https://github.com/canonical/craft-parts/issues/1609
    plugin: cmake
    source: components
    override-build: |

      cp -rf --archive --link --no-dereference ${CRAFT_PART_SRC}/* ${CRAFT_PART_INSTALL}

      # OpenVINO models are only for amd64
      if [ "$CRAFT_ARCH_BUILD_FOR" != "amd64" ]; then
        rm -rf ./model-qwen2-5-vl-3b-instruct-ov-int4/*
        rm -rf ./model-qwen2-5-vl-3b-instruct-ov-int4-npu/*
      fi

      # Ampere models are only for arm64
      if [ "$CRAFT_ARCH_BUILD_FOR" != "arm64" ]; then
        rm -rf ./model-qwen2-5-vl-3b-instruct-aio-q8r16/*
        rm -rf ./mmproj-qwen2-5-vl-3b-instruct-aio-q8-0/*
      fi
    organize:
      "model-qwen2-5-vl-3b-instruct-q4-k-m/*": (component/model-qwen2-5-vl-3b-instruct-q4-k-m)
      "mmproj-qwen2-5-vl-3b-instruct-q8-0/*": (component/mmproj-qwen2-5-vl-3b-instruct-q8-0)
      "model-qwen2-5-vl-7b-instruct-q4-k-m/*": (component/model-qwen2-5-vl-7b-instruct-q4-k-m)
      "mmproj-qwen2-5-vl-7b-instruct-q8-0/*": (component/mmproj-qwen2-5-vl-7b-instruct-q8-0)
      "model-qwen2-5-vl-3b-instruct-aio-q8r16/*": (component/model-qwen2-5-vl-3b-instruct-aio-q8r16)
      "mmproj-qwen2-5-vl-3b-instruct-aio-q8-0/*": (component/mmproj-qwen2-5-vl-3b-instruct-aio-q8-0)
      "model-qwen2-5-vl-3b-instruct-ov-int4/*": (component/model-qwen2-5-vl-3b-instruct-ov-int4)
      "model-qwen2-5-vl-3b-instruct-ov-int4-npu/*": (component/model-qwen2-5-vl-3b-instruct-ov-int4-npu)

    prime:
      # Exclude everything not explicitly organized
      - -*

  llamacpp:
    plugin: dump
    source: 
      - on amd64: https://github.com/canonical/llama.cpp-builds/releases/download/b9611/llamacpp-amd64.tar.gz
      - on arm64: https://github.com/canonical/llama.cpp-builds/releases/download/b9611/llamacpp-arm64.tar.gz
    stage-packages:
      - libgomp1
    override-build: |
      # Move license files to be included in the snap, not the component
      mkdir -p $CRAFT_PRIME/usr/share/doc/
      mv licenses $CRAFT_PRIME/usr/share/doc/llama.cpp

      craftctl default
    organize:
      "*": (component/llamacpp)
    
  llamacpp-cuda:
    plugin: dump
    source:
      - on amd64: https://github.com/canonical/llama.cpp-builds/releases/download/b9611/llamacpp-amd64+cuda12.9.tar.gz
      - on arm64: https://github.com/canonical/llama.cpp-builds/releases/download/b9611/llamacpp-arm64+cuda12.9.tar.gz
    stage-packages:
      - libgomp1
    override-build: |
      # Move license files to be included in the snap, not the component
      mkdir -p $CRAFT_PRIME/usr/share/doc/
      mv licenses $CRAFT_PRIME/usr/share/doc/llama.cpp-cuda

      craftctl default
    organize:
      "*": (component/llamacpp-cuda)

  openvino-model-server:
    plugin: dump
    source: https://github.com/openvinotoolkit/model_server/releases/download/v2026.2/ovms_ubuntu24_2026.2.0_python_off.tar.gz
    stage-packages:
      - libxml2
      - libcurl4
    # This part is only for amd64
    override-pull: &amd64-only |
      [ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ] && craftctl default || exit 0
    override-build: |
      if [ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ]; then
        # Move license files to be included in the snap, not the component
        mkdir -p $CRAFT_PRIME/usr/share/doc/openvino-model-server
        mv thirdparty-licenses $CRAFT_PRIME/usr/share/doc/openvino-model-server/
        mv LICENSE $CRAFT_PRIME/usr/share/doc/openvino-model-server/

        craftctl default
      fi
    override-stage: *amd64-only
    override-prime: *amd64-only
    organize:
      "*": (component/openvino-model-server)

  llama-aio: &llama-aio-part
    source: https://github.com/AmpereComputingAI/llama.cpp/releases/download/v3.4.2/llama_aio_v3.4.2_943aee2.tar.gz
    source-type: tar
    plugin: dump
    stage-packages:
      - libcurl4
    override-pull: &arm64-only |
      [ "$CRAFT_ARCH_BUILD_FOR" == "arm64" ] && craftctl default || exit 0
    override-build: *arm64-only
    override-stage: *arm64-only
    override-prime: *arm64-only
    organize:
      "LICENSE*.txt": usr/share/doc/llama-aio/
      llama-server: (component/llama-aio)/bin/
      libllama.so: (component/llama-aio)/lib/
      "lib*.so*": (component/llama-aio)/lib/
      libmtmd.so: (component/llama-aio)/lib/
      "usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/": (component/llama-aio)/lib/
    prime:
      - -*

  llama-aio-ampereone:
    <<: *llama-aio-part
    source: https://github.com/AmpereComputingAI/llama.cpp/releases/download/v3.4.2/llama_aio_v3.4.2_943aee2_ampereone.tar.gz
    organize:
      "LICENSE*.txt": usr/share/doc/llama-aio-ampereone/
      llama-server: (component/llama-aio-ampereone)/bin/
      libllama.so: (component/llama-aio-ampereone)/lib/
      "lib*.so*": (component/llama-aio-ampereone)/lib/
      libmtmd.so: (component/llama-aio-ampereone)/lib/
      "usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/": (component/llama-aio-ampereone)/lib/

components:
  llamacpp:
    type: standard
    summary: llama.cpp Engine using default CPU instruction sets
    description: LLM inference in C/C++

  llama-aio:
    type: standard
    summary: llama-aio Engine for Ampere Altra CPUs
    description: LLM inference in C/C++

  llama-aio-ampereone:
    type: standard
    summary: llama-aio Engine for Ampere One CPUs
    description: LLM inference in C/C++

  openvino-model-server:
    type: standard
    summary: OpenVINO Model Server
    description: OpenVINO Model Server for serving models

  llamacpp-cuda:
    type: standard
    summary: llama.cpp with CUDA backend
    description: LLM inference in C/C++

  # 
  # Models
  #

  model-qwen2-5-vl-3b-instruct-q4-k-m:
    type: standard
    summary: Qwen 2.5 VL 3B Q4
    description: Quantized model with 3B parameters in gguf format with Q4_K_M weight encoding

  mmproj-qwen2-5-vl-3b-instruct-q8-0:
    type: standard
    summary: MMProj for Qwen 2.5 VL 3B
    description: Multimodal projector for Qwen 2.5 VL 3B

  model-qwen2-5-vl-7b-instruct-q4-k-m:
    type: standard
    summary: Qwen 2.5 VL 7B Q4
    description: Quantized model with 7B parameters in gguf format with Q4_K_M weight encoding

  mmproj-qwen2-5-vl-7b-instruct-q8-0:
    type: standard
    summary: MMProj Qwen 2.5 VL 7B
    description: Multimodal projector for Qwen 2.5 VL 7B

  model-qwen2-5-vl-3b-instruct-aio-q8r16:
    type: standard
    summary: Qwen 2.5 VL 3B Q8_0 for Ampere CPUs
    description: Quantized model with 3B parameters in gguf format with Q8R16 weight encoding

  mmproj-qwen2-5-vl-3b-instruct-aio-q8-0:
    type: standard
    summary: MMProj Qwen 2.5 VL 3B Q8_0 for Ampere CPUs
    description: Multimodal projector for Qwen 2.5 VL 3B with Q8_0 weight encoding

  model-qwen2-5-vl-3b-instruct-ov-int4:
    type: standard
    summary: Qwen 2.5 VL 3B for Intel CPU and Intel GPU
    description: Model with 3B parameters in OpenVINO IR format, quantized with INT4

  model-qwen2-5-vl-3b-instruct-ov-int4-npu:
    type: standard
    summary: Qwen 2.5 VL 3B for Intel NPU
    description: Model with 3B parameters in OpenVINO IR format, quantized with INT4 and symmetric channel wise quantization to run on Intel NPU

apps:
  qwen-vl:
    command: bin/modelctl
    completer: bin/snap-completer.bash
    plugs:
      - hardware-observe
      - opengl
      - network
      - desktop
    environment:
      ADDITIONAL_FEATURES: chat, webui
      OCL_ICD_VENDORS: $SNAP/etc/OpenCL/vendors

  server:
    command: bin/server.sh
    daemon: simple
    plugs:
      # For inference and hardware detection (via init)
      - opengl
      # Needed by for cuda-uvmfd to listen on a unix socket?
      # Needed for server app by inheritance
      - network-bind
      - hardware-observe
      # For sideloading models
      - home 
      # Intel NPU access (device node)
      - intel-npu
      # Intel NPU access (libs) 
      - npu-libs  

  server-webui:
    command: bin/server-webui.sh
    daemon: simple
    plugs:
      - network-bind
