#!/bin/bash -eu

component_directory=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

mmproj_filename="mmproj-Qwen2.5-VL-3B-Instruct-Q8_0.gguf"
mmproj_path=$component_directory/$mmproj_filename
snapctl set mmproj-file-path="$mmproj_path"
