name: cla-check
on: [pull_request]

jobs:
  cla-check:
    runs-on: [ self-hosted, linux, amd64, medium, noble ]
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v2
