name: Snap CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

env:
  SNAP_NAME: qwen-vl

jobs:
  build:
    name: Build
    strategy:
      matrix:
        runs:
          - architecture: amd64
            runner: [ self-hosted, amd64, Linux, noble, large ]
          - architecture: arm64
            runner: [ self-hosted, ARM64, Linux, noble, large ]
    runs-on: ${{ matrix.runs.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download models
        run: |
          curl -L https://huggingface.co/ggml-org/Qwen2.5-VL-3B-Instruct-GGUF/resolve/main/mmproj-Qwen2.5-VL-3B-Instruct-Q8_0.gguf --output $GITHUB_WORKSPACE/components/mmproj-qwen2-5-vl-3b-instruct-q8-0/mmproj-Qwen2.5-VL-3B-Instruct-Q8_0.gguf
          curl -L https://huggingface.co/ggml-org/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/mmproj-Qwen2.5-VL-7B-Instruct-Q8_0.gguf --output $GITHUB_WORKSPACE/components/mmproj-qwen2-5-vl-7b-instruct-q8-0/mmproj-Qwen2.5-VL-7B-Instruct-Q8_0.gguf
          curl -L https://huggingface.co/ggml-org/Qwen2.5-VL-3B-Instruct-GGUF/resolve/main/Qwen2.5-VL-3B-Instruct-Q4_K_M.gguf --output $GITHUB_WORKSPACE/components/model-qwen2-5-vl-3b-instruct-q4-k-m/Qwen2.5-VL-3B-Instruct-Q4_K_M.gguf
          curl -L https://huggingface.co/ggml-org/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf --output $GITHUB_WORKSPACE/components/model-qwen2-5-vl-7b-instruct-q4-k-m/Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.SNAP_NAME}}_${{github.run_number}}_${{matrix.runs.architecture}}
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error

#      - name: Publish snap
#        uses: snapcore/action-publish@v1
#        if: github.ref == 'refs/heads/main'
#        env:
#          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
#        with:
#          snap: ${{ steps.snapcraft.outputs.snap }}
#          release: latest/edge/ci
