name: Testflinger Tests

on:
  workflow_call:
    inputs:
      snap-channel:
        description: Snap channel to test
        required: true
        type: string
  workflow_dispatch:
    inputs:
      snap-channel:
        description: Snap channel to test
        required: true
        type: string

jobs:
  test-multimodal-prompt:
    name: qwen-vl ${{ matrix.jobs.select-engine }}
    strategy:
      fail-fast: false
      matrix:
        jobs:
          - job-queue: maas-systemtests-amd64
            provision-data: "distro: noble"
            select-engine: cpu
            test-chat-tps: true
            test-image-prompt: true

          - job-queue: 202409-35502
            provision-data: "distro: noble"
            select-engine: cpu-avx512
            test-chat-tps: true
            test-image-prompt: true

          - job-queue: mir-intel-noble
            provision-data: "distro: noble"
            select-engine: intel-cpu
            test-chat-tps: true
            test-image-prompt: true

          - job-queue: 202111-29603 # Alder Lake, GPU 8086:4680
            provision-data: "distro: noble"
            select-engine: intel-gpu
            test-chat-tps: true
            test-image-prompt: true

          - job-queue: hp-prodesk-4-sff-g1i-desktop-ai-pc-ag8j7av-c36704
            provision-data: "url: https://tel-image-cache.canonical.com/oem-share/sutton/releases/noble/oem-24.04c/20251009-80/sutton-noble-oem-24.04c-20251009-80.iso"
            install-intel-npu-driver: true
            select-engine: intel-npu
            test-chat-tps: false # npu engine does not work with text only input
            test-image-prompt: true

          - job-queue: anbox-nvidia-amd64
            provision-data: "distro: noble"
            install-nvidia-driver-version: 550
            select-engine: cuda
            test-chat-tps: true
            test-image-prompt: true

          - job-queue: ampere-altra
            provision-data: "distro: noble"
            select-engine: ampere-altra
            test-chat-tps: true
            test-image-prompt: true

          - job-queue: ampere-one
            provision-data: "distro: noble"
            select-engine: ampere-one
            test-chat-tps: true
            test-image-prompt: true

          - job-queue: maas-systemtests-amd64
            provision-data: "distro: noble"
            select-engine: cpu-tiny
            test-chat-tps: true
            test-image-prompt: false # cpu-tiny does not support image input

    uses: canonical/inference-snaps-testing/.github/workflows/test-snap.yaml@v1
    secrets: inherit
    with:
      job-queue: ${{ matrix.jobs.job-queue }}
      provision-data: ${{ matrix.jobs.provision-data }}

      snap-name: qwen-vl
      snap-channel: ${{ inputs.snap-channel }}

      install-nvidia-driver-version: ${{ matrix.jobs.install-nvidia-driver-version }}
      install-intel-npu-driver: ${{ matrix.jobs.install-intel-npu-driver == true }}
      snap-connections: ${{ matrix.jobs.snap-connections }}

      expected-engine: ${{ matrix.jobs.expected-engine }}
      select-engine: ${{ matrix.jobs.select-engine }}

      test-chat-tps: ${{ matrix.jobs.test-chat-tps == true }}
      expected-tps: ${{ matrix.jobs.expected-tps }}

      test-image-prompt: ${{ matrix.jobs.test-image-prompt == true }}
