#!/bin/bash -eu

component_name=model-qwen2-5-vl-3b-instruct-q4-k-m

model_filename=Qwen2.5-VL-3B-Instruct-Q4_K_M.gguf
model_path=$SNAP_COMPONENTS/$component_name/$model_filename
export MODEL_FILE=$model_path

mmproj_filename=mmproj-Qwen2.5-VL-3B-Instruct-Q8_0.gguf
mmproj_path=$SNAP_COMPONENTS/$component_name/$mmproj_filename
export MMPROJ_FILE=$mmproj_path
