#!/bin/bash -eu

component_name=model-qwen2-5-vl-3b-instruct-q4-k-m

model_filename=Qwen2.5-VL-3B-Instruct-Q4_K_M.gguf
model_path=$SNAP_COMPONENTS/$component_name/$model_filename
snapctl set model-file-path="$model_path"

snapctl set model-type=gguf