#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.install"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)

#
# Set generic config
#

snapctl set http.port="8080"
snapctl set http.host="127.0.0.1"
snapctl set verbose="false"

#
# Set all stacks as snap config
# 

$SNAP_NAME load

#
# Auto stack selection
#

if snapctl is-connected hardware-observe; then
    $SNAP_NAME use --auto --assume-yes
elif lscpu -V &> /dev/null; then
    echo "Able to access hardware info without hardware-observe interface connection: assuming dev mode installation."
    $SNAP_NAME use --auto --assume-yes
else
    echo "hardware-observe interface not auto connected. Skip auto stack selection."
fi
